[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"

[[constraint]]
  name = "github.com/regner/albiondata-client"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
