/* concat all tables into `market_orders` */
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `bridgewatch_market_orders`;
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `caerleon_market_orders`;
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `fort_sterling_market_orders`;
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `lymhurst_market_orders`;
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `martlock_market_orders`;
INSERT INTO `market_orders` (`albion_id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at`) SELECT `id`, `item_id`, `quality_level`, `enchantment_level`, `price`, `amount`, `auction_type`, `expires`, `location`, `created_at`, `updated_at`, `deleted_at` FROM `thetford_market_orders`;

/* Set initial_amount (which we didn't have before) to amount */
UPDATE `market_orders` SET `initial_amount` = `amount`;